version: '3'

services:
  postgres:
    image: postgres
    container_name: twitter-postgres 
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=twitter_clone_dev
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local